language: python
install:
- sudo apt-get install python3-dev
- python-config --cflags

- sudo apt-get install swig
- swig -python translate.i
- gcc -fPIC -c translate_wrap.c
- gcc -shared translate_wrap.o -o _trans.so
- ls
- pip install .
script:
- python tests/testvr.py
